//
//  LoginViewController.swift
//  iChat
//
//  Created by Егор Шилов on 25.08.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginViewController: UIViewController {
    
    @IBOutlet private var emailTextField: UITextField!
    @IBOutlet private var passwordTextField: UITextField!
    @IBOutlet private var loginButton: UIButton!
    
    private var viewModel: LoginViewModelProtocol!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
        viewModel = LoginViewModel(view: self)
    }
    
    @IBAction private func loginButtonAction(_ sender: Any) {
        viewModel.loginButtonTapped(
            email: emailTextField.text ?? "",
            password: passwordTextField.text ?? ""
        )
    }
    
    private func setupUI() {
        emailTextField.underlined()
        passwordTextField.underlined()
        passwordTextField.isSecureTextEntry = true
        
        loginButton.configuration?.cornerStyle = .capsule
    }
    
     func alert(with message: String) {
        let alert = UIAlertController(title: "Error", message: message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
        present(alert, animated: true)
    }
}
