//
//  ChatsTableInteractor.swift
//  iChat
//
//  Created by Егор Шилов on 05.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatsBusinessLogic {
    func doSomething(request: Chats.Something.Request)
}

protocol ChatsDataStore {
    var selectedUserInSearchUserView: UserCellViewModel? { get set }
}

class ChatsInteractor: ChatsBusinessLogic, ChatsDataStore {
    
    var presenter: ChatsPresentationLogic?
    var selectedUserInSearchUserView: UserCellViewModel? {
        didSet {
            wasPickedUserInSearchUserView()
        }
    }
    
    func wasPickedUserInSearchUserView() {
//        let response = 
    }
    
    // MARK: Do something
    
    func doSomething(request: Chats.Something.Request) {
        
        let response = Chats.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
