//
//  ChatsTableRouter.swift
//  iChat
//
//  Created by Егор Шилов on 05.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ChatsRoutingLogic {
    func routeToConversation(segue: UIStoryboardSegue?)
}

protocol ChatsDataPassing {
    var dataStore: ChatsDataStore? { get }
}

class ChatsRouter: NSObject, ChatsRoutingLogic, ChatsDataPassing {
    
    weak var viewController: ChatsViewController?
    var dataStore: ChatsDataStore?
    
    // MARK: Routing
    
    func routeToConversation(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! ConversationViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToConversation(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "ConversationViewController") as! ConversationViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToConversation(source: dataStore!, destination: &destinationDS)
            navigateToConversation(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToConversation(source: ChatsViewController, destination: ConversationViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    
    func passDataToConversation(source: ChatsDataStore, destination: inout ConversationDataStore) {
        destination.userInfo = source.userInfo
    }
}
