//
//  ChatsTableModels.swift
//  iChat
//
//  Created by Егор Шилов on 05.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias ChatsViewModelCell = Chats.gettingChats.ViewModel.ChatsViewModelCell

enum Chats {
    // MARK: Use cases
    
    enum gettingChats {
        
        struct Response {
            var rawChats: [ChatModel]
        }
        
        struct ViewModel {
            struct ChatsViewModelCell: CellIdentifiable {
                var cellIdentifier: String {
                    "ChatCell"
                }
                
                let lastMessageDate: String
                let lastMessageText: String
                let username: String
                let fullname: String
                let email: String
                let unreadedMessagesCount: Int
                
                init(chatModel: ChatModel) {
                    lastMessageDate = chatModel.lastMessageDate ?? "Unknown"
                    lastMessageText = chatModel.lastMessageText ?? "No message"
                    username = chatModel.username ?? "Unknown"
                    fullname = chatModel.fullname ?? "Unknown"
                    email = chatModel.email ?? "No email"
                    unreadedMessagesCount = chatModel.unreadedMessagesCount
                }
                
            }
            
            var rows: [CellIdentifiable]
        }
    }
}
