//
//  ChatsTablePresenter.swift
//  iChat
//
//  Created by Егор Шилов on 05.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatsPresentationLogic {
    func presentSomething(response: Chats.Something.Response)
}

class ChatsPresenter: ChatsPresentationLogic {
    
    weak var viewController: ChatsDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Chats.Something.Response) {
        let viewModel = Chats.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
