//
//  SearchUserRouter.swift
//  iChat
//
//  Created by Егор Шилов on 01.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchUserRoutingLogic {
    func routeToConversation(segue: UIStoryboardSegue?)
}

protocol SearchUserDataPassing {
    var dataStore: SearchUserDataStore? { get }
}

class SearchUserRouter: NSObject, SearchUserRoutingLogic, SearchUserDataPassing {
    
    weak var viewController: SearchUserViewController?
    var dataStore: SearchUserDataStore?
    
    // MARK: Routing
    
    func routeToConversation(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! ConversationViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToConversation(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "ConversationViewController") as! ConversationViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToConversation(source: dataStore!, destination: &destinationDS)
            navigateToConversation(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToConversation(source: SearchUserViewController, destination: ConversationViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    
    func passDataToConversation(source: SearchUserDataStore, destination: inout ConversationDataStore) {
        destination.userInfo = (source.selectedUser as! UserCellViewModel)
    }
}
