//
//  SearchUserRouter.swift
//  iChat
//
//  Created by Егор Шилов on 01.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchUserRoutingLogic {
    func routeToChats(segue: UIStoryboardSegue?)
}

protocol SearchUserDataPassing {
    var dataStore: SearchUserDataStore? { get }
}

class SearchUserRouter: NSObject, SearchUserRoutingLogic, SearchUserDataPassing {
    
    weak var viewController: SearchUserViewController?
    var dataStore: SearchUserDataStore?
    
    // MARK: Routing
    
    func routeToChats(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! ChatsViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToChats(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "ChatsViewController") as! ChatsViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToChats(source: dataStore!, destination: &destinationDS)
            navigateToChats(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToChats(source: SearchUserViewController, destination: ChatsViewController) {
        source.navigationController?.dismiss(animated: true, completion: nil)
    }
    
    // MARK: Passing data
    
    func passDataToChats(source: SearchUserDataStore, destination: inout ChatsDataStore) {
        destination.selectedUserInSearchUserView = (source.selectedUser as! UserCellViewModel)
    }
}
