//
//  SearchUserInteractor.swift
//  iChat
//
//  Created by Егор Шилов on 01.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchUserBusinessLogic {
    func getUsersData(request: SearchUser.Search.Request)
}

protocol SearchUserDataStore {

}

class SearchUserInteractor: SearchUserBusinessLogic, SearchUserDataStore {
    
    var presenter: SearchUserPresentationLogic?
    
    // MARK: Getting List Of Users From Database
    
    func getUsersData(request: SearchUser.Search.Request) {
        FireBaseDatabaseManager.shared.searchUser(username: request.searchText ?? "") { [unowned self] users in
            
            let response = SearchUser.Search.Response(users: users)
            presenter?.presentUsers(response: response)
        }
    }
}
