//
//  SearchUserPresenter.swift
//  iChat
//
//  Created by Егор Шилов on 01.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchUserPresentationLogic {
    func presentSomething(response: SearchUser.Something.Response)
}

class SearchUserPresenter: SearchUserPresentationLogic {
    
    weak var viewController: SearchUserDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: SearchUser.Something.Response) {
        let viewModel = SearchUser.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
