//
//  SearchUserInteractor.swift
//  iChat
//
//  Created by Егор Шилов on 01.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchUserBusinessLogic {
    func doSomething(request: SearchUser.Something.Request)
}

protocol SearchUserDataStore {

}

class SearchUserInteractor: SearchUserBusinessLogic, SearchUserDataStore {
    
    var presenter: SearchUserPresentationLogic?
    
    // MARK: Do something
    
    func doSomething(request: SearchUser.Something.Request) {
        
        let response = SearchUser.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
