//
//  SearchUserModels.swift
//  iChat
//
//  Created by Егор Шилов on 01.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias UserCellViewModel = SearchUser.Search.ViewModel.UserCellViewModel


protocol CellIdentifiable {
    var cellIdentifier: String { get }
}

enum SearchUser {
    // MARK: Use cases
    
    enum Search {
        struct Request {
            var searchText: String?
        }
        
        struct Response {
            var users: [UserModel]
        }
        
        struct ViewModel {
            struct UserCellViewModel: CellIdentifiable {
                var cellIdentifier: String {
                    "UserCell"
                }
                
                let fullName: String
                let username: String
                
                init(user: UserModel) {
                    self.fullName = "\(user.name ?? "No name") \(user.surname ?? "No surname")"
                    self.username = user.username ?? "No username"
                }
            }
            
            let rows: [CellIdentifiable]
        }
    }
}
