//
//  SearchUserPresenter.swift
//  iChat
//
//  Created by Егор Шилов on 01.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchUserPresentationLogic {
    func presentUsers(response: SearchUser.Search.Response)
}

class SearchUserPresenter: SearchUserPresentationLogic {
    
    weak var viewController: SearchUserDisplayLogic?
    
    // MARK: PresentUsers
    
    func presentUsers(response: SearchUser.Search.Response) {
        var rows: [UserCellViewModel] = []
        
        response.users.forEach { userModel in
            rows.append(UserCellViewModel(user: userModel))
        }
        
        let viewModel = SearchUser.Search.ViewModel(rows: rows)
        viewController?.presentUsers(viewModel: viewModel)
    }
}
