//
//  ConversationPresenter.swift
//  iChat
//
//  Created by Егор Шилов on 05.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ConversationPresentationLogic {
    func presentUserFullname(response: Conversation.fullnameLabel.Response)
    func presentMessages(response: Conversation.messages.Response)
}

class ConversationPresenter: ConversationPresentationLogic {
    
    weak var viewController: ConversationDisplayLogic?
    var worker: ConversationPresenterWorkerMessagesSorting?

    // MARK: presentUserFullName
    
    func presentUserFullname(response: Conversation.fullnameLabel.Response) {
        let viewModel = Conversation.fullnameLabel.ViewModel(fullname: response.fullname)
        viewController?.displayFullname(viewModel: viewModel)
    }
    
    func presentMessages(response: Conversation.messages.Response) {
        worker = ConversationPresenterWorkerMessagesSorting()
        let sortedData = worker?.sortMessages(rawMessages: response.rawMessages)
        
        let messages = sortedData?.0
        let headersDate = sortedData?.1
        
        
    }
}
