//
//  ConversationInteractor.swift
//  iChat
//
//  Created by Егор Шилов on 05.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ConversationBusinessLogic {
    
}

protocol ConversationDataStore {
    var userInfo: UserCellViewModel? { get set }
}

class ConversationInteractor: ConversationBusinessLogic, ConversationDataStore {
    
    var userInfo: UserCellViewModel? {
        didSet {
            let response = Conversation.fullnameLabel.Response(fullname: userInfo?.fullName ?? "Unkown")
            presenter?.presentUserFullname(response: response)
            
            getMessages(with: userInfo?.email ?? "")
        }
    }
    
    func getMessages(with email: String) {
        var rawMessages: [MessageModel] = [] {
            didSet {
                let response = Conversation.messages.Response(rawMessages: rawMessages)
                presenter?.presentMessages(response: response)
            }
        }
        
        FireBaseDatabaseManager.shared.getMessages(withEmail: email, andLimit: 25) { arrayOfMessages in
            rawMessages.append(contentsOf: arrayOfMessages)

        }
    }
    
    var presenter: ConversationPresentationLogic?
}
