//
//  ConversationInteractor.swift
//  iChat
//
//  Created by Егор Шилов on 05.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ConversationBusinessLogic {
    func doSomething(request: Conversation.Something.Request)
}

protocol ConversationDataStore {
    var userInfo: UserCellViewModel? { get set }
}

class ConversationInteractor: ConversationBusinessLogic, ConversationDataStore {
    
    var userInfo: UserCellViewModel? {
        didSet {
//            print("ewq")
        }
    }
    
    var presenter: ConversationPresentationLogic?
    var worker: ConversationWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Conversation.Something.Request) {
        worker = ConversationWorker()
        worker?.doSomeWork()
        
        let response = Conversation.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
