//
//  ConversationInteractor.swift
//  iChat
//
//  Created by Егор Шилов on 05.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ConversationBusinessLogic {
    func sendMessage(request: Conversation.SendMessage.Request)
    func getMessages(isNeedToUpLimit: Bool)
    func stopObservingMessages()
}

protocol ConversationDataStore {
    var userInfo: ConversationUserModel? { get set }
}

class ConversationInteractor: ConversationBusinessLogic, ConversationDataStore {
    
    private var limitOfMessages = 25 // limit on the number of messages we need
    
    // MARK: Getting Needed User Information from Another View by Routing
    
    var userInfo: ConversationUserModel? {
        didSet {
            let response = Conversation.fullnameLabel.Response(fullname: userInfo?.fullName ?? "Unkown")
            presenter?.presentUserFullname(response: response)
            
            getMessages(isNeedToUpLimit: false)
        }
    }
    
    // MARK: Get Messages From Database
    
    func getMessages(isNeedToUpLimit: Bool) {
        guard FireBaseDatabaseManager.shared.isPaginating == false else { return }
            if isNeedToUpLimit == true {
                limitOfMessages += 25 // Its needed when user scrolls to top of collection view
            }
        
        var rawMessages: [MessageModel] = [] {
            didSet {
                guard rawMessages.isEmpty == false else { return }
                let response = Conversation.Messages.Response(rawMessages: rawMessages)
                presenter?.presentMessages(response: response)
            }
        }
                
        FireBaseDatabaseManager.shared.getMessages(withEmail: userInfo?.email ?? "", andLimit: limitOfMessages) { arrayOfMessages in
            rawMessages = []
            rawMessages.append(contentsOf: arrayOfMessages)
        }
    }
    
    // MARK: Send Message to Database
    
    func sendMessage(request: Conversation.SendMessage.Request) {
        guard userInfo != nil else { return }
        guard request.messageText != "" && request.messageText != "Message" else { return }
        FireBaseDatabaseManager.shared.removeConversationsObserver(with: userInfo?.email ?? "")
        FireBaseDatabaseManager.shared.sendMessage(to: userInfo!.email, withName: userInfo!.fullName, andUsername: userInfo!.username, message: request.messageText)
        getMessages(isNeedToUpLimit: false)
    }
    
    // MARK: When view disappear database stops the observer for messages
    
    func stopObservingMessages() {
        FireBaseDatabaseManager.shared.removeConversationsObserver(with: userInfo?.email ?? "")
    }
    
    var presenter: ConversationPresentationLogic?
}
