//
//  SignUpViewController.swift
//  iChat
//
//  Created by Егор Шилов on 26.08.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SignUpViewController: UIViewController {
    @IBOutlet private var emailTextField: UITextField!
    @IBOutlet private var passwordTextField: UITextField!
    

    var viewModel: SignUpViewModelProtocol!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        viewModel = SignUpViewModel()
        setupUI()
    }
    
    @IBAction private func signUpButtonAction(_ sender: Any) {
        
    }
    
    @objc private func textFieldDidChange() {
        viewModel.checkMailIsValid(email: emailTextField.text ?? "")
        updateEmailValidImage(with: viewModel.emailIsValid ? "checkmark" : "xmark")
    }
    
    func alert(message: String) {
        let alert = UIAlertController(title: "Error", message: message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
        present(alert, animated: true)
    }
    
    private func setupUI() {
        viewModel.viewModelDidChanged = { [unowned self] model in
            viewModel = model
        }
        
        emailTextField.underlined()
        passwordTextField.underlined()
        
        emailTextField.addTarget(self, action: #selector(textFieldDidChange), for: .editingChanged)
    }
    
    private func updateEmailValidImage(with imageName: String) {
        emailTextField.rightViewMode = UITextField.ViewMode.always
        let imageView = UIImageView(frame: CGRect(x: 0, y: 0, width: 20, height: 20))
        var image = UIImage(systemName: imageName)
        imageView.image = image
        
        if imageName == "xmark" {
            imageView.tintColor = .red
        } else {
            imageView.tintColor = .green
        }
        
        emailTextField.rightView = imageView
    }
}

