//
//  MessengerViewController.swift
//  iChat
//
//  Created by Егор Шилов on 01.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MessengerDisplayLogic: AnyObject {
    func displaySomething(viewModel: Messenger.Something.ViewModel)
}

class MessengerViewController: UITableViewController, MessengerDisplayLogic {
    
    var interactor: MessengerBusinessLogic?
    var router: (NSObjectProtocol & MessengerRoutingLogic & MessengerDataPassing)?
    
    var searchController = UISearchController()

    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
        doSomething()
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: SetupUI
    
    private func setupUI() {
        MessengerConfigurator.shared.configure(view: self)
    }
    
    // MARK: Do something
    
    func doSomething() {
        let request = Messenger.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: Messenger.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
