//
//  MessengerPresenter.swift
//  iChat
//
//  Created by Егор Шилов on 31.08.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MessengerPresentationLogic {
    func presentSomething(response: Messenger.Something.Response)
}

class MessengerPresenter: MessengerPresentationLogic {
    
    weak var viewController: MessengerDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Messenger.Something.Response) {
        let viewModel = Messenger.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
