//
//  MessengerConfigurator.swift
//  iChat
//
//  Created by Егор Шилов on 01.09.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MessengerConfigurator {
    static let shared = MessengerConfigurator()
    
    func configure(view: MessengerViewController) {
        let interactor = MessengerInteractor()
        let presenter = MessengerPresenter()
        let router = MessengerRouter()
        view.interactor = interactor
        view.router = router
        interactor.presenter = presenter
        presenter.viewController = view
        router.viewController = view
        router.dataStore = interactor
    }
}
